timeout: '600s'

steps:
- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/void-battery/v0']
  env:
  - 'DOCKER_BUILDKIT=1'

- id: Check Versions
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: ['web/maybe.sh', 'touch', 'needs-update']

- id: Maybe Push
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args: ['-c', '! test -f needs-update || docker push gcr.io/void-battery/v0']

- id: Maybe Deploy
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: bash
  args: ['-c', '! test -f needs-update || web/deploy.sh']
