timeout: '600s'

steps:
- id: Patcher Docker
  name: 'gcr.io/cloud-builders/docker'
  dir: patcher
  entrypoint: bash
  args: ['./build-docker.sh']

- id: Patch
  name: 'gcr.io/cloud-builders/docker'
  dir: patcher
  entrypoint: bash
  args: ['./launch-docker', './main.sh']

- id: Release
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  dir: patcher
  args: ['./release.sh']

- id: Build Docker Image
  name: 'gcr.io/cloud-builders/docker'
  dir: web
  entrypoint: bash
  args: ['maybe.sh', 'docker', 'build', '.', '-t', 'asia.gcr.io/void-battery/v0']

- id: Push Docker Image
  name: 'gcr.io/cloud-builders/docker'
  dir: web
  entrypoint: bash
  args: ['maybe.sh', 'docker', 'push', 'asia.gcr.io/void-battery/v0']

- id: Maybe deploy
  name: 'gcr.io/cloud-builders/gcloud'
  dir: web
  entrypoint: bash
  args: ['maybe.sh', './deploy.sh']
