load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "extract",
    srcs = ["extract.cpp"],
    copts = ["-std=c++17"],
    local_defines = ["BAZEL_BUILD"],
    data = ["@ooz//:libooz_so"],
    visibility = ["//patcher:__subpackages__"],
    deps = [
        "@ooz//:libbun",
        "@rules_cc//cc/runfiles",
    ],
)
