on:
  push:
    branches: [main]
  pull_request:
name: docker

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: docker build .
      env:
        DOCKER_BUILDKIT: 1
