on: [push, pull_request]
name: patcher

defaults:
  run:
    working-directory: patcher

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - run: go test -v ./...

  patcher:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
    - uses: actions/checkout@v2
    - run: ./alpine-main.sh
