on:
  push:
    branches: [main]
  pull_request:
name: test

jobs:
  patcher-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    - run: bazel test //patcher/dat/types:types_test

  web-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true

    - run: bash fetch.sh
      working-directory: patcher
    - run: bash main.sh
      working-directory: patcher
    - run: bash release.sh
      working-directory: patcher

    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - run: python -m pip install -r requirements.txt -r test-requirements.txt
      working-directory: web
    - run: python -m pytest tests
      working-directory: web
      timeout-minutes: 2
    - run: xvfb-run python -m pytest integration_test.py
      working-directory: web
      timeout-minutes: 2
